config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :url_mappers

  root "home#index"

  post   "/login",       to: "sessions#create"
  get    "/signup",   to: "users#new"
  post   "/signup",   to: "users#create"
  get    "/dashboard", to: "users#dashboard"
  delete "/logout", to: "sessions#destroy"
  get    "/:slug", to: "home#redirect_actual_url"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url_mapper.rb
class UrlMapper < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :url, format: URI::DEFAULT_PARSER.make_regexp(%w[http https]), presence: true

  before_create :add_slug

  def new_token
    loop do
      token = SecureRandom.base64(8)
      break token unless UrlMapper.where(slug: token).exists?
    end
  end

  def add_slug
    self.slug = new_token
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_secure_password
  validates :first_name, :last_name, presence: true, length: { maximum: 254 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }, presence: true, length: { maximum: 254 }
  validates :password, :password_confirmation, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def digest(string)
    ActiveModel::SecurePassword.min_cost ? cost = BCrypt::Engine::MIN_COST : cost = BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def new_token
    SecureRandom.urlsafe_base64
  end

  def admin?
    admin
  end

  def remember
    self.remember_token = new_token
    update_attribute(:remember_digest, digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :authenticate_user

  protected

  def authenticate_user
    return if logged_in?

    flash[:danger] = "Please log in."
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user

  def index
    if current_user.present?
      redirect_to dashboard_path
    end
  end

  def redirect_actual_url
    url_mapper = UrlMapper.find_by(slug: params[:slug])
    if url_mapper.present?
      redirect_to url_mapper.url, allow_other_host: true
    else
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user


  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in(user)
      remember(user)
      redirect_to dashboard_path
    else
      flash[:errors] = ["Invalid email/password combination"]
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/url_mapper_controller.rb
class UrlMapperController < ApplicationController
end

app/controllers/url_mappers_controller.rb
class UrlMappersController < ApplicationController
  def index
    @url_mappers = UrlMapper.all
  end

  def new
    @url_mapper = UrlMapper.new
  end

  def create
    @url_mapper = UrlMapper.new(url_mapper_params)
    if @url_mapper.save
      redirect_to dashboard_path
    else
      binding.pry
      flash[:errors] = @url_mapper.errors.full_messages
      render 'new'
    end
  end

  def edit
    @url_mapper = UrlMapper.find(params[:id])
  end


  def update
    @url_mapper = UrlMapper.find(params[:id])
    if @url_mapper.update(url_mapper)
      redirect_to dashboard_path, flash: { success: ["url has been updated successfully."] }
    else
      render 'edit', flash: { errors: @url_mapper.errors.full_messages }
    end
  end

  def destroy
    @url_mapper = UrlMapper.find(params[:id])
    if @url_mapper.destroy
      redirect_to dashboard_path, flash: { success: ["url has been successfully deleted."] }
    else
      redirect_to dashboard_path, flash: { errors: @url_mapper.errors.full_messages }
    end
  end

  def url_mapper_params
    params.require(:url_mapper).permit(:title, :url, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user

  def new
    @user = User.new
  end

  def dashboard
    @url_mappers = UrlMapper.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      binding.pry
      log_in(@user)
      remember(@user)
      redirect_to dashboard_path
    else
      flash[:errors] = @user.errors.full_messages
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Mandala Trading"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def admin?
    current_user&.admin?
  end

 
  def allow_delete_access?
    admin?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    session.delete(:user_session_id)
    @current_user = nil
  end
end

app/helpers/url_mapper_helper.rb
module UrlMapperHelper
end

app/helpers/url_mappers_helper.rb
module UrlMappersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= render 'layouts/error_messages' %>
<div class="page-wrapper d-flex justify-content-center align-items-center">
  <h3>Welcome</h3>
</div>

<%= render template: "sessions/new" %>

app/views/layouts/_error_messages.html.erb
<% flash[:errors]&.each do |message| %>
<div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
  <div class="toast" style="position: absolute; top: 0; right: 0;">
    <div class="toast-body">
      <%= message %>
    </div>
  </div>
</div>
<% end %>


<script>
 $(document).ready(function() {
    $(".toast").toast('show');
  });
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between pt-0 pb-0">

    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown ml-auto">
        <a class="nav-link d-flex align-items-center dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="user-initial"><%= "#{current_user.first_name[0]}#{current_user.last_name[0]}" %></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Logout", logout_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure to logout?'}, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="//code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pdfobject/2.1.1/pdfobject.min.js"></script>
    <script src="//code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    
    <!-- JS, Popper.js, and jQuery -->
    <script src="//cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js"></script>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <section class="root-wrapper">

    

      <%= yield %>
      
    </section>
  </body>
</html>

app/views/url_mappers/_form.html.erb
<div class="page-wrapper">
  <div class="container">
    <div class="row">
      <div class="offset-xl-2 col-xl-8">
        <%=  form_for @url_mapper do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id  %>
          <div class="row mx-n1">
            <div class="col-xl-12 px-1">
              <div class="form-group">
                <%= f.label :title, class: "label text-dark" %>
                <%= f.text_field :title, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="row mx-n1">
            <div class="col-xl-12 px-1">
              <div class="form-group">
                <%= f.label :url, class: "label text-dark" %>
                <%= f.text_field :url, required: true, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="text-right">
            <button name="button" type="submit" class="btn btn-primary mt-2 btn-block">
              create
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/url_mappers/edit.html.erb
<%= render 'layouts/navbar'%>
<%= render 'layouts/error_messages' %>
<%= render 'form' %>

app/views/url_mappers/new.html.erb
<%= render 'layouts/error_messages' %>
<%= render 'form' %>

app/views/users/_form.html.erb
<div class="page-wrapper">
  <div class="container">
    <h3 class="text-center text-dark pb-2"> Login</h3>
    <div class="row">
      <div class="offset-xl-2 col-xl-8">
        <%=  form_for :user, url: signup_path do |f| %>
          <div class="row mx-n1">
            <div class="col-xl-12 px-1">
              <div class="form-group">
                <%= f.label :first_name, class: "label text-dark" %>
                <%= f.text_field :first_name, required: true, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="row mx-n1">
            <div class="col-xl-12 px-1">
              <div class="form-group">
                <%= f.label :last_name, class: "label text-dark" %>
                <%= f.text_field :last_name, required: true, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="row mx-n1">
            <div class="col-xl-12 px-1">
              <div class="form-group">
                <%= f.label :email, class: "label text-dark" %>
                <%= f.email_field :email, autofocus: true, required: true, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="row mx-n1">
            <div class="col-xl-12 px-1">
              <div class="form-group">
                <%= f.label :password, class: "label text-dark" %>
                <%= f.password_field :password, required: true, class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="row mx-n1">
            <div class="col-xl-12 px-1">
              <div class="form-group">
                <%= f.label :password_conformation, class: "label text-dark" %>
                <%= f.password_field :password_conformation, required: true, class: "form-control" %>
              </div>
            </div>
          </div>


          <div class="text-right">
            <button name="button" type="submit" class="btn btn-primary mt-2 btn-block">
              signup
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<%= render 'layouts/navbar'%>
<%= render 'layouts/error_messages' %>

<div class="d-flex">
  <%= link_to "add", new_url_mapper_path, class: "mt-5 ml-auto mr-5 btn btn-danger" %>
</div>

<div class="px-5 mt-2">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">title</th>
      <th scope="col">url</th>
      <th scope="col">slug</th>
      <th scope="col">action</th> 
    </tr>
  </thead>
  <tbody>
    <% @url_mappers.each do |url_mapper| %>
      <tr>
        <td><%= url_mapper.title %></td>
        <td><%= url_mapper.url %></td>
        <td><%= url_mapper.slug %></td>
        <td>
         <%= link_to "edit", edit_url_mapper_path(url_mapper), class: "btn btn-info"%>
         <%= link_to "delete", url_mapper, class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: 'Are you sure to delete?'}%>
        </td>
      </tr>
    <% end %>
  <tbody>
</table>
<div>

app/views/users/new.html.erb
<%= render 'layouts/error_messages' %>
<%= render 'form' %>